// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwG05lq0zCOZvRZ1FWuAi6agjFZ89_GMs',
    appId: '1:801265881917:web:764a16b488b89f5ba72b54',
    messagingSenderId: '801265881917',
    projectId: 'cycle-project-6d252',
    authDomain: 'cycle-project-6d252.firebaseapp.com',
    storageBucket: 'cycle-project-6d252.appspot.com',
    measurementId: 'G-CD53JFW967',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFgW2P8g---mAh3aRPoWF3QqbyVJqrOk',
    appId: '1:801265881917:android:47d38c634de2c524a72b54',
    messagingSenderId: '801265881917',
    projectId: 'cycle-project-6d252',
    storageBucket: 'cycle-project-6d252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5ChZpUBX7CmArGkPWHd_KbGiCGNLspE',
    appId: '1:801265881917:ios:1989b84a3c4097f1a72b54',
    messagingSenderId: '801265881917',
    projectId: 'cycle-project-6d252',
    storageBucket: 'cycle-project-6d252.appspot.com',
    iosBundleId: 'com.example.cycleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5ChZpUBX7CmArGkPWHd_KbGiCGNLspE',
    appId: '1:801265881917:ios:1989b84a3c4097f1a72b54',
    messagingSenderId: '801265881917',
    projectId: 'cycle-project-6d252',
    storageBucket: 'cycle-project-6d252.appspot.com',
    iosBundleId: 'com.example.cycleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwG05lq0zCOZvRZ1FWuAi6agjFZ89_GMs',
    appId: '1:801265881917:web:1b65cd86fd015fc3a72b54',
    messagingSenderId: '801265881917',
    projectId: 'cycle-project-6d252',
    authDomain: 'cycle-project-6d252.firebaseapp.com',
    storageBucket: 'cycle-project-6d252.appspot.com',
    measurementId: 'G-TEKKD8F5CK',
  );
}
